import os
import glob

configfile: " config.yaml"
include: "rules/bowtie2.smk"
include: "rules/fastqc.smk"
include: "rules/samToBamSorted.smk"
include: "rules/markDup.smk"
include: "rules/filterBam.smk"
include: "rules/bamToBw.smk"

Sample,Read = glob_wildcards("data/{sample}_{read}.fastq.gz")

rule all:
    input:
        expand("{sample}/fastqc/{sample}_{read}_fastqc.{extension}", sample=Sample,read=Read,extension=["zip","html"]),
        expand("{sample}/bowtie2/unfiltered_aligned.{extension}", sample=Sample, extension=["sam","txt"]),
        expand("{sample}/bowtie2/UnfilAlignedSortByCoord.bam", sample=Sample),
        expand("{sample}/bowtie2/aligned_rmdup.bam", sample=Sample),
        expand("{sample}/bowtie2/aligned_rmdupPrimary.{extension}", sample=Sample,extension=["bam","bam.bai"]),
        expand( "{sample}/bw/{sample}.bw", sample=Sample)
